import "./globals.css";

import type { Metadata } from "next";
import type { FC, PropsWithChildren } from "react";
import { Poppins } from "next/font/google";
import { cn } from "@/lib/utils";

const font = Poppins({ weight: ["400", "500", "600", "700"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body suppressHydrationWarning={true} className={cn("antialiased", font.className)}>
      {children}
    </body>
  </html>
);

export default RootLayout;
export { metadata };
